### ISSUE TITLE
Publish coverage reports?

### ISSUE THREAD

**Issue by hidroh** [Microsoft/thrifty#132]
Now that we have Jacoco maybe we can also get a nice badge to display coverage? These are 2 options that I know:
- [coveralls.io](https://coveralls.io/), here is a [sample report](https://coveralls.io/github/kt3k/coveralls-gradle-plugin)
- [codecov.io](https://codecov.io/), here is a [sample report](https://codecov.io/gh/javaslang/javaslang-jackson)

Integration should be straightforward for public Github project that builds using Travis. Though for a multi-project setup codecov seems to be easier.
- [coveralls integration guide](https://github.com/kt3k/coveralls-gradle-plugin)
- [codecov integration guide](https://github.com/codecov/example-gradle)

**Comment by benjamin-bader** [comment]
I looked at coveralls since I've used it before, but Gradle projects have no official support so I passed.  Didn't know about codecov.io, I'll take a look - thanks!
