### ISSUE TITLE
Generate Kotlin code

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/thrifty#143]
KotlinPoet makes this feasible; given prior experience with the language, it feels like we could make some nice improvements.

There's a lot to consider here:
- What language patterns can we use to tighten up generated structs/consts/etc?
- Can we make the Thrifty runtime friendlier to idiomatic Kotlin?  An example where it is less than friendly is the assumption that builders and adapters are nested classes.
- Can we just use data classes for built structs?  Should we?
- Is this even a worthwhile pursuit?  If not, what would make it so?

**Comment by hzsweers** [comment]
Scattered thoughts

- data classes for structs
- global vals for consts
- typealias for typedefs
- sealed classes for unions
- sealed classes for responses
  - This is the really neat one IMO. Exceptions are structs, response type on services themselves are structs. Return a sealed class of the combined types and let the user `when` on it with the adapter handling the intermediate layer

i.e. 

```thrift
exception UnAuthorized {

}

struct MyResponse {

}

service Tweeter {
  TweetResponse tweet(1:Tweet tweet) throws (1:TwitterUnavailable unavailable )
}
```

```kotlin
// Generated
sealed class TweetResult

  class TweetResponse : TweetResult

when (result) {
  is MyResponse -> ...
  is UnAuthorized -> ...
}
```

**Comment by benjamin-bader** [comment]
I've begun work in this direction; the first step IMO will be porting the current codebase to Kotlin.  It's not a strict requirement, but in my experience it helps to consider the domain (thrift and Kotlin) from multiple lenses.  Porting code is an excellent such lens.

I'm not yet sure about all of the individual scattered thoughts above, but I really like the notion of representing responses as sealed classes.  It certainly makes my job easier to decouple Thrift exceptions from JVM exceptions, and (in theory) gives much more control to users.  Who knows, maybe most people will prefer to continue receiving exceptions the old-fashioned way, but having choices seems like a nice win.

One complication to the model is that all responses carry the possibility of a generic `ThriftException`.  Either we duplicate the heck out of this construct (icky, but _maybe_ OK in generated code), or we end up with a matryoshka doll of a response.  Worse, sealed classes currently all must be defined in the same file, so it actually won't even be possible to include `ThriftException` in this scheme.  I've only thought about this for a little while, so maybe there's an elegant solution that I'm missing?

I guess we could always add a generic error case containing the `ThriftException` data; I'm cautious about this idea because it exposes us to potential name clashes with user-defined result types, but I'm not totally opposed either.

**Comment by hzsweers** [comment]
Another thought - would be really great if UserType was a sealed class. If you want to avoid dumping everything into one file, you could define just interfaces and implement them elsewhere

For the sealed classes thing on exceptions, maybe you could leverage something similar for defining the APIs and implementing them elsewhere?

**Comment by hzsweers** [comment]
Sorry - not interfaces, but abstract classes

**Comment by benjamin-bader** [comment]
It sounds like I'm missing something wrt sealed classes.  How do abstract classes help?  We could certainly declare a sealed class that extends an abstract class from elsewhere, but then the compiler exhaustiveness checks are much dumber and will always require an `else`.

I agree that UserType, or even all of the type-types, would be great as sealed types.  My dream here is to completely remove the need for visitors, and this feels like the best way to do it.

**Comment by hzsweers** [comment]
I just mean in the sense that you could define them in one file and put full implementations somewhere else to avoid the "dumping everything in one file" issue

**Comment by benjamin-bader** [comment]
This is mostly done as of #183.  The big missing piece is generating RPC service clients; I'd like to make use of coroutines here, but don't yet feel confident in either my own experience with them or in the available options for fine-grained IO, which are all apparently still experimental.  Maybe after a few more weeks with 1.3-M1 things will become more clear to me.

**Comment by benjamin-bader** [comment]
I feel good calling this issue Done; RPC client codegen has landed, and the rest of this list would be good to have but are not essential.  I'll open separate issues to track them.
