### ISSUE TITLE
Remove unreferenced objects

### ISSUE THREAD

**Issue by bangarharshit** [Microsoft/thrifty#159]
Currently thrifty generates the object for all the structs in an include thrift files even if they are not used.
```thrift
// example.thrift
namespace java com.foo.bar

include "referenced.thrift"

struct Query {
  1: required string text,
  2: optional i64 resultsNewerThan
  3: optional referenced.Used used
}

struct SearchResult {
  1: required string url,
  2: required list<string> keywords = [], // A list of keywords related to the result
  3: required i64 lastUpdatedMillis // The time at which the result was last checked, in unix millis
}

service Google {
  list<SearchResult> search(1: Query query)
}
```
```thrift
//referenced.thrift
namespace java com.foo.bar2

struct Used {
  1: optional string identifier
}

struct Unused {
  1: optional string identifier
}
```

In the example above the struct unused is not used but a java class is generated (input is `example.thrift`). 

On a similar note, do you think if it makes sense for thrifty to support some kind of service whitelisting (ex - you want to whitelist only 10 services and everything referenced by those)?

**Comment by benjamin-bader** [comment]
Proguard does this out-of-the-box; are you able to use it?

Given that reducing method-count is the main goal of this project, my assumption has been that folks are already stripping out unused code.  Do you have a use-case where Proguard doesn't apply?

**Comment by bangarharshit** [comment]
I can't think of any specific case where proguard may fail (if he is not using model normally and just using in deserialization which is via reflection the deserialization may then crash but can be wrapped in a catch - this is true only for deserializers outside thrifty).

I don't have much idea about how big of an effort this will be(I can try prototyping something over the coming weekend, if you have any idea it will be great if you can point to that) but if it is not a very big effort it can lead to much conciseness even at debug time.

**Comment by benjamin-bader** [comment]
In my opinion, it's premature to talk about implementation ease/difficulty.  The main question in my mind is whether there's a concrete use-case to justify the work - if so, then it makes more sense to talk about how hard it might be to implement.

Android developers should only really care about eliminating unused code when approaching dex limitations (method refs, classes, etc).  Proguard is the first and best tool available for the purpose.  Why should we attempt to re-implement it?  I don't see why or how we'd do a better job.  It would be more useful for our generated code to become Proguard-friendly (as in #158), to the extent that it is possible.

Without a definite use-case, I'm not inclined to accept what would be a complicated and hard-to-debug feature.  We'd be taking on definite, real, complexity for hypothetical and under-specified gains.

**Comment by bangarharshit** [comment]
Got it.
