### ISSUE TITLE
Generate `Nullable` for all fields in a union

### ISSUE THREAD

**Issue by bangarharshit** [Microsoft/thrifty#160]
Currently, thrifty checks that ` a number of fields set= 1` for unions but doesn't annotate the fields with Nullable. 

It can be a useful indication for devs as well as tools like infer/NullAway. We can use this blog post if the resulting code is too cluttered  - https://medium.com/square-corner-blog/non-null-is-the-default-58ffc0bb9111

**Comment by benjamin-bader** [comment]
Adding nullable to union fields would definitely be an improvement!  I'd be happy to accept a PR - it would be quite simple to modify ThriftyCodeGenerator#buildStruct to do this.

**Comment by bangarharshit** [comment]
@benjamin-bader added PR for the union. 

Do you also want to support non-null by default? It may reduce the clutter but not sure how useful will it be for generated code. All it needs is to get rid of NonNull annotation and create a package-info.java for all the generated packages.

**Comment by benjamin-bader** [comment]
Thanks for the PR!  I just realized that we already did emit nullable annotations for unions, but with your change, that's now explicit - our codebase is more robust thanks to it.

I don't think nonnull-by-default is worth worrying about - these annotations don't do much to obscure the generated code (which, after all, is _generated_ code).  We value its readability, but only to a certain point.  Is there a use-case here, beyond producing more aesthetically-pleasing code?

**Comment by bangarharshit** [comment]
None, Apart from lesser boilerplate. 

TBH, I agree that for the generated code it is ok to use @NonNull everywhere and adds to the complexity. Most of the static code analysis tools such as infer and nullaway supports both. Closing the ticket. Feel free to re-open the ticket if you feel it is worth it.

Thanks.
