### ISSUE TITLE
Support for case format LOWER_CAMEL in naming convention

### ISSUE THREAD

**Issue by bangarharshit** [Microsoft/thrifty#163]
Currently, thrifty has 2 policies for field name - DEFAULT and JAVA. [Checkstyle](http://checkstyle.sourceforge.net/config_naming.html#MemberName ) by default and mostly configured to check for lowerCamelCase in java.

How about a `third` naming policy for lowerCamelCase? We can use guava's CaseFormatter to determine the current [case format](https://github.com/google/guava/issues/2212). If it is not equal to CaseFormatter.LOWER_CAMEL convert to the same.

Should be very trivial.

**Comment by benjamin-bader** [comment]
`FieldNamingPolicy.JAVA` already does lower-camel-case, unless the field begins with a capitalized acronym.  This conforms with standard Java naming style.  How would `FieldNamingPolicy.LOWER_CAMEL` differ?

**Comment by bangarharshit** [comment]
This particular unit test failed:
```java
    @Test
    public void defaultNamesAreUnaltered() {
        FieldNamingPolicy policy = FieldNamingPolicy.DEFAULT;

        assertThat(policy.apply("SSLFlag"), is("SSLFlag"));
        assertThat(policy.apply("MyField"), is("MyField"));
        assertThat(policy.apply("ssl_field"), is("sslField")); // It fails
    }
```

```
java.lang.AssertionError: 
Expected: is "sslField"
     but: was "ssl_field"
Expected :sslField
Actual   :ssl_field
 <Click to see difference>
```

The current FieldNamingPolicy.java just makes first character lower case if it is not part of some acronym.
```java
if (Character.isUpperCase(name.charAt(0))) {
                if (name.length() == 1 || !Character.isUpperCase(name.charAt(1))) {
                    name = Character.toLowerCase(name.charAt(0)) + name.substring(1);
                }
            }
            return name;
```

**Comment by benjamin-bader** [comment]
Ah, I see - I think it's reasonable for the `JAVA` policy to convert snake_case to camelCase.

**Comment by bangarharshit** [comment]
Ideally, Java should handle this case but it will break backward compatibility for anyone using the same in production.  How about deprecating the JAVA policy and introducing a new naming policy?

**Comment by benjamin-bader** [comment]
That's true, but I'm OK with that outcome.  I don't think anyone who has snake-cased thrifts is using the java-style naming policy - as you notice, it simply doesn't do anything useful in that case.  We can call out the breakage in release notes, but I doubt anyone will actually be broken.

**Comment by hzsweers** [comment]
Note that guava's case formatting doesn't play nice with acronyms, which forced us to move away from it
