### ISSUE TITLE
Bug in loading paths - checking ".thrift" extension on `Path` types

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#177]
In `Loader`, when loading paths it filters on `.endsWith(".thrift")`. Thing is, it's checking this on `Path` and converting the given parameter to a `Path`. The result is that this filter always fails to find any `.thrift` files:

https://github.com/Microsoft/thrifty/blob/103614bd7e5102a69dc87258d5dee657fa4810ad/thrifty-schema/src/main/java/com/microsoft/thrifty/schema/Loader.java#L194

**Comment by benjamin-bader** [comment]
Yep, great catch.  Include-path scanning seems to have been broken since the Java 8 update.  Thanks for the report, and for the fix!
