### ISSUE TITLE
Broken code generation for services that extends other services

### ISSUE THREAD

**Issue by stefanodacchille** [Microsoft/thrifty#18]
# Description

Let's say we define a `service` `Foo`:

```thrift
service Foo {
  void foo()
}
```
and another service `Bar` which extends `Foo`:

```thrift
include 'Foo.thrift'

service Bar extends Foo {
  void bar()
}
```

The generated code for the `BarClient` should provide an implementation of the `foo` method in order for the generated code to compile but currently only an implementation for `bar` is generated.

**Comment by stefanodacchille** [comment]
There are currently no tests to check the code generation, correct? I saw `ThriftyCodeGeneratorTest.java` but it's ignored.

**Comment by benjamin-bader** [comment]
I'll confess that we don't actively use service inheritance, so my apologies in shipping a broken feature.

Unit-testing codegen seems quite fragile to me; I'm less interested, say, in the order methods are generated than I am that the methods do what I want them to do.  As you've noted, we aren't running unit tests on the output of codegen - instead, I rely on `thrift-integration-test` for testing actual functionality.

Clearly, the tests didn't cover service inhertance!

**Comment by stefanodacchille** [comment]
We stopped using it too. But unfortunately our services all inherit from a
base one - with only one method, sigh - so I cannot avoid it.

**Comment by benjamin-bader** [comment]
I believe this is a very simple fix - it is embarrassing not to have caught it sooner :/

**Comment by stefanodacchille** [comment]
Thanks Ben, that was quick!
