### ISSUE TITLE
Kotlin codegen: sealed classes for responses

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/thrifty#201]

**Comment by hzsweers** [comment]
One problem we've run into with this internally is that responses often share exceptions, like unauthorized

**Comment by benjamin-bader** [comment]
You're right - that's a fatal point against this feature, for now.

I seem to recall a conversation where someone said that it was possible for sealed classes to have interfaces, i.e.

```
sealed class Foo

interface Bar : Foo()
```

I suppose one could take a shared exception class and make it implement Bar.Foo for each distinct Bar, but personally I don't think this would be useful - it'd be pretty gross, and verbose to boot.  I'm inclined to consider this issue closed, unless a better idea comes along.

**Comment by hzsweers** [comment]
I don't see how, from a java standpoint that's not valid code since sealed classes are `abstract` classes and you can't make an interface extend an abstract class o_O

**Comment by benjamin-bader** [comment]
Meh, closing this out as "wontfix".
