### ISSUE TITLE
Consider @Generated annotations

### ISSUE THREAD

**Issue by jparise** [Microsoft/thrifty#233]
The [`@Generated`](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html) annotation is a signal that a Java source file has been generated programatically. It is used by some static analysis tools, and some code review interfaces automatically "collapse" diffs touching generated files.

It also provides a standard way to include metadata, such as a timestamp. Thrifty currently writes this information as a file comment.

There might be a small cost to including this additional annotation, but I'm not experienced enough in those aspects of today's JVMs to estimate it.

**Comment by benjamin-bader** [comment]
It sounds like a good idea - I wasn't aware that CR tools treated it specially.  Since it is part of the standard JDK (I think?) and has "source" retention, it's not present at all in bytecode and imposes no cost either at runtime or compile-time.

Should be a no-brainer to implement.

**Comment by benjamin-bader** [comment]
Ah, I remember now - we initially did this, then removed the annotations because (absent tool support) they cause tons of noise in code-reviews for teams that check in generated sources.  If we add them back, it should be accompanied by an option to suppress them.

**Comment by jparise** [comment]
Could you expand on that a little bit? Our team checks in generated sources, and we do see some level of noise related to code moving around and the timestamp comment changing. Reducing that noise is my main motivation for proposing `@Generated` because our code review tool (at least) collapses files containing the `@Generated` string.

A compromise might be to just include the literal string `@Generated` in the generated file's header comment, which is what Apache Thrift does.

**Comment by benjamin-bader** [comment]
Sure - per the javadoc, well-formed `@Generated` annotations include a timestamp.  This means that when a .thrift file is updated, _all_ generated code files are touched instead of only those that have meaningful changes.  If code-review tools aren't aware of this annotation, then any review will be dominated by meaningless autogenerated changes.  The simplest solution for us was to just omit the annotation entirely.

We could probably leave the timestamp out, come to think of it - I don't know of any tool that depends on it.  I'd prefer that over going back to comments-as-annotations.

**Comment by jparise** [comment]
That works for me. I can also solve the "auto-collapse in code review" thing locally; `@Generated` just happens to already work.

Are there any other benefits of using the `@Generated` annotation that we haven't covered before we move on? I've been led to understand that some IDEs might treat those files differently (because with regard to refactoring actions?), but I don't have specific examples.

**Comment by jparise** [comment]
One more example is that some linters skip `@Generated` code automatically, rather than having to configure an explicit exclusion. That may or may not be useful to some users.

**Comment by jparise** [comment]
Lastly, I think it would be fine to use the `@Generated` annotation with an empty `date` field. It defaults to `""`, and while it might be preferred, it doesn't appear to be required.

**Comment by jparise** [comment]
Also, regarding "commit noise", the current file header comment includes a `Source:` line with the file path to the source `.thrift` file. Because we check that into source control, that line can also vary based on the machine on which the code generation was performed (i.e. the path can differ slightly).

**Comment by jparise** [comment]
> There's also a switch to disable file comments, for exactly that reason.

Ah! I see `emitFileComment`, but it doesn't appear to be available as a compiler command line argument. Should it be?

**Comment by jparise** [comment]
I'll submit a Pull Request that adds a command line flag for that.

**Comment by jparise** [comment]
This looks good! Time for Thrifty 1.0.0-RC2?

**Comment by benjamin-bader** [comment]
Yes, thanks for the reminder.  I'll try to do it today.

**Comment by benjamin-bader** [comment]
Done
