### ISSUE TITLE
Support collection type annotations in UUID tracking

### ISSUE THREAD

**Issue by ZacSweers** [microsoft/thrifty#277]
They're apparently legal thrift! https://github.com/Microsoft/thrifty/pull/274/files

Not sure if there's much to do here though since they're not user elements

**Comment by benjamin-bader** [comment]
Can you expand on what's needed here?  I'm not so familiar with the UUID stuff, so I can't tell  what, or whether there's even anything, to do.

**Comment by ZacSweers** [comment]
I think it was that the UUID tracking used to tag elements right now doesn't tag them, so you can't track them.

**Comment by benjamin-bader** [comment]
Ah, I see now, parsed annotations aren't derived from UserElement and so they have no UUID ergo cannot be tracked.

It doesn't sound simple to accommodate tracking annotations.  I'm not personally able to spend very much time these days, with a kid and a new job.  Can you think of anyone who would need this and be willing to do the work?  If not, I'd probably rather just close this as "wontfix".

**Comment by benjamin-bader** [comment]
wontfix
