### ISSUE TITLE
Parser fails when throws keyword is on the next line

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#28]
The following fails during parsing:

```thrift
GetStuffResponse getStuff(
  1: required GetStuffRequest request;
) 
throws (
  1: NotAuthorizedException notAuthorized;
  2: NotFoundException notFound;
  3: InvalidRequestException invalidRequest;
)
```

but this passes:

```thrift
GetStuffResponse getStuff(
  1: required GetStuffRequest request;
) throws (
  1: NotAuthorizedException notAuthorized;
  2: NotFoundException notFound;
  3: InvalidRequestException invalidRequest;
)
```

Specifically, it tries to read `throws` as an identifier rather than recognize it as a keyword continuing from the previous block. Not sure if this is a parser issue or if thrift specs require `throws` keywords to be on the same line following the previous block.

**Comment by benjamin-bader** [comment]
Thrift is "wonderfully underspecified", and to be honest I can't really tell if `throws` *must* be on the same line, or if the IDL doc merely looks that way.  Have you tried them both on the Apache implementation?  Does it work there?  I'm inclined to match its behavior either way.

**Comment by hzsweers** [comment]
Yup looks like it supports having `throws` on the next line

**Comment by benjamin-bader** [comment]
Thanks for verifying; we should do the same.
