### ISSUE TITLE
EnumType's findMemberByName/id methods say they return null, but actually can't

### ISSUE THREAD

**Issue by ZacSweers** [Microsoft/thrifty#283]
This would make them actually through a NSE rather than return null. Could make them return `null` with `firstOrNull`, but not sure if that would constitute an API breaking change

```kotlin
/**
 * Find the [member][EnumMember] with the given [name], or null.
 */
fun findMemberByName(name: String): EnumMember {
    return members.first { it.name == name }
}

/**
 * Find the [member][EnumMember] with the given [id], or null.
 */
fun findMemberById(id: Int): EnumMember {
    return members.first { it.value == id }
}
```

Fix

```kotlin
/**
 * Find the [member][EnumMember] with the given [name], or null.
 */
fun findMemberByName(name: String): EnumMember? {
    return members.firstOrNull { it.name == name }
}

/**
 * Find the [member][EnumMember] with the given [id], or null.
 */
fun findMemberById(id: Int): EnumMember? {
    return members.firstOrNull { it.value == id }
}
```

**Comment by benjamin-bader** [comment]
Thanks for your patience - I forgot to respond to this issue.

I think these comments have always been lies.  [Here's the Java version of these functions](https://github.com/Microsoft/thrifty/blob/5f75345fabe399c5e6e14b18825d2445decfa501/thrifty-schema/src/main/java/com/microsoft/thrifty/schema/EnumType.java), as of 0.3.2 (shortly before the Kotlin rewrite); notice that they throw NSEs, as does the current implementation.

I'd vote for just updating the documentation, personally.  I'm certainly not aware of any code that expects or accounts for a nullable result here.
