### ISSUE TITLE
Proposal: support alternate compiler/codegen/servicebuilder setups

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#29]
The project's actually well-suited for this, all I had to do was make them and put them in the same package space where the normal ones would go. This would allow developers to take advantage of the wonderful parsing support you all have already written, while being able to generate their own models/services that fit their needs.

**Comment by benjamin-bader** [comment]
I'm open to this.  How would these setups look, API-wise?

As you've noted, the project is split out into fine-grained modules already, and parsing support can be had by just depending on `thrifty-schema` (which includes parsing and linking, but no codegen).  What would you want to build on top of this?

**Comment by hzsweers** [comment]
Honestly, might be simple enough just to make methods public. Let me put together a list.

**Comment by hzsweers** [comment]
Here's what I'm thinking:

* ConstantBuilder
* TypeResolver
* TypeNames
* SimpleVisitor

Not exhaustive, but that's all I personally ended up needing. Maybe try with just that and see if other needs/cases come up?

**Comment by benjamin-bader** [comment]
SimpleVisitor and TypeNames, as trivial as they are, I guess are very easy to make public.

I'm reluctant to make the other two public.  They are implementation details, especially ConstantBuilder - it's hard for me to see how they could be useful as part of a public API, and I wouldn't want to commit to maintaining their interfaces going forward.  It's not an absolute no, but I'd want a large benefit from it that I just don't see right now.

At a higher level, what would you like to do?  What would these types being public enable?  You hinted at the wish for a more pluggable compilation process; what are you trying to do?

**Comment by hzsweers** [comment]
it's not very organized as I was putting it up for a coworker to look at, but basically this: https://github.com/hzsweers/thrifty/commit/5b3fd111670b8484daace84c46360396e8a324fb

Ideally, what I want is to be able to parse and load all the thrift information that schema and compiler handle, and be able to generate whatever code I want from it. In this case, I have a working implementation of generating autovalue-friendly code instead, and separately have also implemented support for the services generation and wrapped it all up in a gradle plugin.

It looks like the only things needed from ConstantBuilder are usages in the code generator's `buildConst` method. The TypeResolver is used in a lot of places though for its `getJavaClass` method. I'm not really sure what the best solution would be API-wise.

**Comment by benjamin-bader** [comment]
It looks like this was resolved when Warren added builders - correct?

**Comment by hzsweers** [comment]
Yep!
