### ISSUE TITLE
command line thrifty compiler 1.0.1-SNAPSHOT having the same issue? no main manifest attribute

### ISSUE THREAD

**Issue by aravindanbalan** [Microsoft/thrifty#306]
https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/thrifty/thrifty-compiler/1.0.1-SNAPSHOT/

Hi I am using 1.0.1-SNAPSHOT as suggested here #https://github.com/Microsoft/thrifty/issues/267 to generate the java files but still I am getting the same error

Command:
java -jar thrifty-compiler-1.0.1-20190213.181610-36.jar --out=../src/main/java/xyz/abc/thrift/   multi.thrift

Error: 
no main manifest attribute, in thrifty-compiler-1.0.1-20190213.181610-36.jar

**Comment by benjamin-bader** [comment]
[this](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/thrifty/thrifty-compiler/1.0.1-SNAPSHOT/thrifty-compiler-1.0.1-20190207.070622-33-all.jar) is the file you want.

You're using an _unshaded_ jar, which has only a small part of the total compiler bundled in.  I admit that this isn't well documented right now; I expect that most folks using this project are building the jar themselves, or incorporating it into a compiler-plugin project.  The jar linked above is shaded and contains all necessary manifests, dependency classes, etc required to run.

Please let me know how it goes.

**Comment by aravindanbalan** [comment]
@benjamin-bader Hi Thanks for the jar and it worked. 

I am looking for an example to start a test server listening on a port similar to this one https://github.com/strat0sphere/ThriftTutorial/blob/master/multiplicationService/src/MultiplicationServer.java as an android sticky service and listen on a port. I am not able to achieve the same using Thrifty. 

Is there any example you can point me to where I can write a client and a server that is listening on a port using Thrifty library?

**Comment by benjamin-bader** [comment]
Glad to hear it!

Thrifty has no server component, so you won't be able to replicate this example.

In the thrifty integration tests, we use Thrifty for the client (the thing being tested), but use Apache Thrift for the server (`thrifty-integration-tests` for the former, `thrifty-test-server` for the latter).

**Comment by androidovshchik** [comment]
You can download jar from here https://repo1.maven.org/maven2/com/microsoft/thrifty/thrifty-compiler/2.1.1/thrifty-compiler-2.1.1-all.jar
