### ISSUE TITLE
[BUG] non-ascii characters are broken in Simple JSON protocol

### ISSUE THREAD

**Issue by henryzx** [microsoft/thrifty#316]
non-ascii characters in string are broken when encoding struct to json using SimpleJsonProtocol.

```
   "autocomplete_suggestion_display_strings": [
      "San Francisco, California",
      "Beijing � z\/�1P",
      "Montreal � 1|�Plus?�",
      "New York � S�",
      "\u0005� � S�",
      "�� � S�",
```
After search, I find that the cause is casting java character directly to byte in this method:
```
    @Override
    public void writeString(String str) throws IOException {
        writeContext().beforeWrite();

        int len = str.length();
        UnsafeByteArrayOutputStream baos = new UnsafeByteArrayOutputStream(len);

...
            } else {
                baos.write(c);
                           ^ this method accepts a char but directly cast to byte and store into a bytearray
            }
        }

...
    }
```

```
public synchronized void write(int b) {
        ensureCapacity(count + 1);
        buf[count] = (byte) b;
                       ^ direct cast happens here
        count += 1;
    }
```

I suggest to use a utf8 encoder to encode char to bytes

**Comment by benjamin-bader** [comment]
Thanks for the report!  I'm sorry to say that I can't tell what the original characters should be.  Would you please let me know what kind of input results in the broken output?

I can definitely see in the code that we aren't handling non-ASCII characters in this class.  UTF-8 encoding seems like the wrong approach to me, as json strings are strings of characters, not strings of bytes.  We ought to be able to just use `\uXXXX` escape sequences.

**Comment by benjamin-bader** [comment]
Well, thinking about it more, it does seem like we can lean on UTF-8 here.  Transports deal in bytes, not characters, so the Protocol is in charge of coding in this case.  I should have a fix soon.

**Comment by benjamin-bader** [comment]
I've just merged a fix; it should be available now in snapshot builds, and will be in the final 2.0.0 release whenever I get around to publishing it.

**Comment by henryzx** [comment]
Thanks for fixing this!
