### ISSUE TITLE
Add option to not throw on unknown enum values

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/thrifty#320]
We would instead use the default value specified in thrift (if the field has one), or null for optional/unrequired fields.  We'd still have to throw for required fields without a default, but I'm OK with that - the design of enums in thrift isn't forward-compatible as is, and required fields doubly so.

See #84 for the conversation sparking this feature.

**Comment by deepanshu-zendrive** [comment]
We also ran into the same issue. For now, we've forked the codegen to do this. If you want, I can send a PR for this.

I'm not sure if there should be an option for this, or using the default (or null) should be the only supported way.

**Comment by benjamin-bader** [comment]
If I'm totally honest, I have to say that I do not fully agree with this feature - at least, not as formulated, because it irretrievably loses data.  In protobuf, for example, generated parsers skip over enum values that are unrecognized, BUT those unrecognized values are maintained in the associated "unknown fields", and when re-serialized those messages will have the unrecognized enum value intact.

Thrift has no such concept, so if the server (in the android case) sends an enum value the client doesn't recognize, there's no way to get that value back.  This is on top of the fact that, by going with a default, the client is unintelligently overriding whatever the server is trying to say.

I'd be happy to take a PR for this though, provided that its changes are behind a compiler switch of some sort.

In the linked thread, we talked about adding a command-line flag that, when enabled, would cause generated parsers, on encountering an unrecognized enum value, to:
a) fall back on the field's default value, if specified in thrift
b) fall back on `null` if the field is optional,
c) throw as it currently does for required fields.
