### ISSUE TITLE
Publish release 2.0?

### ISSUE THREAD

**Issue by deepanshu-zendrive** [microsoft/thrifty#329]
There are a bunch of new features in 2.0 - especially androidx support.  Can a final version of 2.0 please be released?

I know that rc has been available for a long time, but a final build will be appreciated.

**Comment by benjamin-bader** [comment]
Hi, thanks for the reminder!  It's been crazy busy for the past N months so I haven't had the attention span to devote to 2.0.  Thanks for your patience - it has indeed been long overdue

I'll take a look this evening and see what remains before a final 2.0 - I want to say that there was something major, but I can't recall just this second.

**Comment by jparise** [comment]
@benjamin-bader just wanted to send a gentle reminder about this. 😉

**Comment by benjamin-bader** [comment]
Done!  2.0.0 should be live in Maven Central now.

In my experience there's always some odd but obvious bug to spoil a nice round version number like this; please let me know as soon as you find it!

**Comment by deepanshu-zendrive** [comment]
Thank you very much Ben for doing this.

**Comment by jparise** [comment]
I'm seeing this with the 2.0.0 artifacts when running `com.microsoft.thrifty.compiler.ThriftyCompiler` from a Gradle task within an Android Studio project:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/microsoft/thrifty/schema/antlr/AntlrThriftLexer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Perhaps related to the OpenJDK changes (#321)? 2.0.0-RC1 continues to work fine.

**Comment by arjitsrivastava** [comment]
> Done! 2.0.0 should be live in Maven Central now.
> 
> In my experience there's always some odd but obvious bug to spoil a nice round version number like this; please let me know as soon as you find it!

Did we officially jinx ourselves here? :)

**Comment by benjamin-bader** [comment]
and _there's_ the bug!  I believe that this is due to my local JDK asserting its dominance.  I built this release with JDK 11, which explains the higher classfile version.  I'll have to figure out how to redo it with Java 8 :/

**Comment by jparise** [comment]
@benjamin-bader maybe a 2.0.1 release built using Java 8 would be the easiest solution?

**Comment by benjamin-bader** [comment]
Yes, I agree, just need to make time to go figure out how to have two jdks side by side, and do the dance.

**Comment by benjamin-bader** [comment]
Thanks for bearing with me - work is nuts and so is my toddler.  I've just pushed 2.0.1 to Maven Central and it ought to be available within the next 10 minutes or so.  Please let me know how it works for you.

**Comment by arjitsrivastava** [comment]
@benjamin-bader The Gradle build does not fail, so that's good news.  Thank you so much for doing this in these beyond crazy times. Really, really appreciate it. 🥇 

We're integrating 2.0.1 and would let you know if we face any other issues.

**Comment by jparise** [comment]
@benjamin-bader It's working for us, too. Thank you!

When you have a free moment, would you mind pushing a `2.0.1` tag for completeness?
