### ISSUE TITLE
Thrifty compiler jar in 2.0.1 is a fat jar

### ISSUE THREAD

**Issue by deepanshu-zendrive** [microsoft/thrifty#363]
For some reason, the 2.0.1 is a fat jar that contains the classes for all other dependencies. This is very apparent when you look at the size when compared to the 2.0.0-RC1 version:

```
-rw-r--r--  1 deepanshu  staff    20K Aug 27  2019 2.0.0-RC1/e18e2c2a611b30d5de472cf6fddee3c16d704d09/thrifty-compiler-2.0.0-RC1.jar
-rw-r--r--  1 deepanshu  staff    22M May 13 22:13 2.0.1/d8320ed69eb0f89c220566814cad2a8cbefb8c85/thrifty-compiler-2.0.1.jar
```

The side effect is that if someone wants to use it in a project with a different version of guava or some other dependency, it will be difficult. 

Not sure what was the difference in compiling 2.0.0-RC1 and 2.0.0, but filing this issue so that it can be investigated before doing the next release.

**Comment by deepanshu-zendrive** [comment]
The snapshots don't seem to have this problem:
```
-rw-r--r--  1 deepanshu  staff    21K Jun  4 13:09 2.0.2-SNAPSHOT/8f65912acdf620a3f3d593a91fa172c1200201f8/thrifty-compiler-2.0.2-SNAPSHOT.jar
```

**Comment by benjamin-bader** [comment]
That's strange; we have an `-all` classifier that is supposed to be the fat jar.  I'll see what broke in the build script.

**Comment by benjamin-bader** [comment]
Yeah, when I do a fresh build this is what I get:
```
~/D/thrifty ❯❯❯ ls -hal thrifty-compiler/build/libs/                                                                                                                                                                  
total 26M
drwxr-xr-x 4 benbader 128 Jun  8 11:23 .
drwxr-xr-x 6 benbader 192 Jun  8 11:22 ..
-rw-r--r-- 1 benbader 25M Jun  8 11:23 thrifty-compiler-2.0.2-SNAPSHOT-all.jar
-rw-r--r-- 1 benbader 22K Jun  8 11:22 thrifty-compiler-2.0.2-SNAPSHOT.jar
```

Must be a problem with the `uploadArchives` task.

**Comment by benjamin-bader** [comment]
I double-checked the commit history, and it looks like I added the current publishing system (the `gradle-maven-publish-plugin`) _after_ the most recent full release.  As best as I can tell, the next release won't have this issue.  I'll keep it open until then, and will double-check before publishing.

**Comment by benjamin-bader** [comment]
I'm preparing the 2.1.0 release, and can confirm that this is no longer an issue, as seen in this Sonatype screenshot:

<img width="523" alt="image" src="https://user-images.githubusercontent.com/512212/84179632-1d531d00-aa3b-11ea-89b0-389eec126ba7.png">
