### ISSUE TITLE
Add sourceFiles to thrifty-gradle-plugin

### ISSUE THREAD

**Issue by jparise** [microsoft/thrifty#365]
The Gradle plugin currently supports parsing directories of `.thrift` source files via `sourceDir` / `sourceDirs`. In our environment, we only want to select specific `.thrift` files out of a source directory.

I don't know Gradle enough to estimate how easy it would be to add something like a `sourceFiles` directive:

```gradle
sourceFiles 'path/to/file.thrift', 'path/to/another/file.thrift'
```

... but that would be a good fit for our use case.

**Comment by benjamin-bader** [comment]
Funny.  That's what I had at first, and figured it'd be too verbose and nobody would want to use it that way.  I'm happy to have `sourceFiles`.

**Comment by benjamin-bader** [comment]
...of course it isn't really that simple to add, now that I think about it.  The nice thing about `sourceDirs` is that they map neatly to Gradle's `SourceDirectorySet`, the thing that more-or-less leads to IntelliJ recognizing directories as containing sources belonging to your project.

It's going to be kind of tricky to coordinate having both `sourceDirs` and `sourceFiles`, the latter of which may not be in any named `sourceDir`, and making that reconciliation work with Gradle's various lifecycle stages.  I'll have to think about it.

**Comment by benjamin-bader** [comment]
I just now noticed your comment, and wish that I had read it sooner - just landed on your exact suggestion.  The current syntax will continue to work as-is but you'll be able to provide a block with `include` and `exclude` statements taking glob expressions:

```
srcDir "path/to/thrifts" // will continue to work

// Or, you could do:
srcDir("path/to/thrifts") {
  include "a.thrift"
  include "b.thrift"
  include "**/constants.thrift"
}
```

I'm still working out the details; Gradle is particular as always.
