### ISSUE TITLE
Support for THttpClient Transport

### ISSUE THREAD

**Issue by cyber-gh** [microsoft/thrifty#370]
Are there any plans to support the THttpClient from the original thrift implementation?

**Comment by benjamin-bader** [comment]
No current plans, but that's only because we haven't had that need.  I'm not opposed to it, but don't personally have the time or inclination to do the work myself.  I'd be happy to help guide a PR.

**Comment by cyber-gh** [comment]
I will give it a try, but this may take some time, as I have to document on this in topic

**Comment by clayreimann** [comment]
@benjamin-bader I'm also interested in seeing this happen (especially given the server-side thrift stuff that looks to be landing soon). Can you point me to the places that I should start looking to build the new transport?

**Comment by benjamin-bader** [comment]
Most transports live in https://github.com/microsoft/thrifty/tree/master/thrifty-runtime/src/commonMain/kotlin/com/microsoft/thrifty/transport.

For convenience you might start putting your code here, but I see a few issues to be resolved prior to merging:
- this is "common" code and most HTTP libraries are platform-specific.  Maybe OkHttp is multiplatform now?
- a main goal of this project is to be as lightweight as possible in terms of method references.  It may be desirable to put this transport into its own module.

**Comment by luqasn** [comment]
I think this can be close now as it was added in https://github.com/microsoft/thrifty/pull/449 :)

**Comment by benjamin-bader** [comment]
Done!
