### ISSUE TITLE
Proposal: Make generated structs implement an interface

### ISSUE THREAD

**Issue by seanabraham** [Microsoft/thrifty#39]
My use case involves serializing any struct without knowing the specific class. In order to do this, they need to implement a common interface. In this case, I imagine the interface will be something like the following:

```java
public interface Struct<T, B extends StructBuilder<T>> {
    Adapter<T, B> getAdapter();
}
```

Then a given generated would look like the following:

```java
public final class Foo implements Struct<Foo, Foo.Builder> {
  public static final Adapter<Foo, Builder> ADAPTER = new FooAdapter();

  ...
  
  @Override
  public Adapter<Foo, Builder> getAdapter() {
    return ADAPTER;
  }

  ...
}
```

and you'd be able to serialize a generic struct via something like:

```java
<T extends Struct<T, B>, B extends StructBuilder<T>> void serialize(T struct) {
  Buffer buffer = new Buffer();
  Transport transport = new BufferTransport(buffer);
  Protocol protocol = new BinaryProtocol(transport);

  struct.getAdapter().write(protocol, struct)
}
```

Since generated structs don't currently extend from or implement any interfaces, I don't imagine this would cause any breakage.

I'm happy to submit a PR that accomplishes this, I believe it would be pretty straight forward.

**Comment by benjamin-bader** [comment]
Serializing generic thrifts would be a very useful feature; we didn't do it initially to save the extra method per class, but I'm not at all opposed in principle.

I'd be happy to take a PR.

**Comment by seanabraham** [comment]
Actually on second thought, a Struct itself wouldn't need to return the whole Adapter because if you already have an instance of the struct you wouldn't be doing any reading. It would just need to write out to a Protocol so this interface can be simplified a bit. I'll put up a PR shortly with that in mind! Let me know what you think.
