### ISSUE TITLE
Add MPP-compatible mode to thrifty-kotlin-codegen

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/thrifty#401]
In order to make multiplatform work, generated code needs to meet certain requirements.  Chiefly, it needs to use _only_ types available in multiplatform code.  Most notably that rules out `IOException`, but there are almost certainly others.

The job here, then is to
a) audit generated kotlin code for JVM-only types, including those in thrifty-runtime like `AsyncClientBase`, and
b) eliminate/mitigate their use (or make the thrity-runtime type an `expect` class, probably).

**Comment by benjamin-bader** [comment]
Let's add `@Generated` to the list.

**Comment by benjamin-bader** [comment]
`@Generated` has been toast for some time now.  With the three PRs merged yesterday, I believe there's nothing left to do.  A manual examination of imports in our generated integration-test code proves this out:

```kt
import com.microsoft.thrifty.Struct
import com.microsoft.thrifty.TType
import com.microsoft.thrifty.ThriftException
import com.microsoft.thrifty.ThriftField
import com.microsoft.thrifty.kotlin.Adapter
import com.microsoft.thrifty.protocol.MessageMetadata
import com.microsoft.thrifty.protocol.Protocol
import com.microsoft.thrifty.service.AsyncClientBase
import com.microsoft.thrifty.service.MethodCall
import com.microsoft.thrifty.service.ServiceMethodCallback
import com.microsoft.thrifty.service.TMessageType
import com.microsoft.thrifty.util.ObfuscationUtil
import com.microsoft.thrifty.util.ProtocolUtil
import kotlin.Any
import kotlin.Boolean
import kotlin.Byte
import kotlin.Double
import kotlin.Exception
import kotlin.Int
import kotlin.Long
import kotlin.Result
import kotlin.Short
import kotlin.String
import kotlin.Throwable
import kotlin.Throws
import kotlin.Unit
import kotlin.collections.ArrayList
import kotlin.collections.LinkedHashMap
import kotlin.collections.LinkedHashSet
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.Set
import kotlin.coroutines.suspendCoroutine
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic
import okio.ByteString
import okio.IOException
```

The only imports that raise eyebrows here are `kotlin.jvm.JvmField` and `kotlin.jvm.JvmStatic`.  On investigation, it turns out that these are `expect annotation class` annotated with `@OptionalExpectation`.  This annotation means that it isn't necessary to have `actual` implementations on all platforms; on those platforms for which no actual exists, the annotation is simply removed by the compiler.  TL;DR, they are no-ops on non-JVM platforms and are safe to leave in.

**Comment by benjamin-bader** [comment]
No sooner do I mark this "done" than I discover that empty unions have a hashCode of `javaClass.hashCode()`, which _also_ needs to be fixed.

**Comment by xiaobailong24** [comment]
Good!🚀🚀
