### ISSUE TITLE
typedef annotations are not parsed in schema if the annotation precedes the newName

### ISSUE THREAD

**Issue by hzsweers** [Microsoft/thrifty#41]
The following typedef reports no annotations when I try to parse it. This appears to be valid thrift ordering in our other language parsers.

```thrift
typedef i64 (js.type = 'Date') Date
```

**Comment by benjamin-bader** [comment]
I agree, this is valid Thrift that annotates the source type of the typedef.  I think this stems from a misreading of the Apache Thrift parser definition which at first glance only allows annotations following the typedef name; in reality, source-type annotations are also accepted as part of the `TypeName` grammar element.

Annotations on types generally are poorly supported in Thrifty; I'll think about how we can be better about it.  While this undoubtedly is a correctness bug, it's curious that this is an issue for you - what's the impact on an Android project?

**Comment by hzsweers** [comment]
Our server guys currently use this basically as a heuristic that the i64 type is actually going to be sent over the wire as an RFC3339-style date String (*groan*), so we want to watch for this annotation in model gen to know that we should parse it as a `Date` in Java in the adapter layer.

**Comment by benjamin-bader** [comment]
Seems like it would make more sense to pass an ISO string and parse as needed in clients/servers, but... ¯\_(ツ)_/¯

For the narrow case of typedefs it seems simple to pass annotations through.

**Comment by hzsweers** [comment]
yeah, looking at the code it seems like there should just be some sort of `peekAnnotations()` or something, just to check if annotations are the next element vs assuming it's the new name

**Comment by hzsweers** [comment]
Digging further, it looks like the annotations are eagerly parsed while resolving the type in `readTypeName()`, but this gets hidden in the final type. My quick-and-dirty proposal is to take one if either exists (that is, if annotations on the parsed typename exists, take them, otherwise try to take trailing ones if they exist).

Let me know what you think. In the meantime, I can cheat in code gen and reflectively pull out the underlying `element` and get the annotation I was looking for.

<img width="942" alt="screen shot 2016-07-20 at 2 32 14 am" src="https://cloud.githubusercontent.com/assets/1361086/16982068/cde3a622-4e22-11e6-9859-51453ec14020.png">

**Comment by benjamin-bader** [comment]
How fascinating!  As it turns out, I misread my own code, and not the Thrift grammar at all.  *sigh*.  A goldfish has a longer memory than I do.  Of course annotations are parsed for type names.

I'd actually prefer it if we added `Typedef#sourceTypeAnnotations()`.  Actually, now that I think on it, this is an excellent dodge around the more general problem of annotations on typenames being destroyed at link-time (https://github.com/Microsoft/thrifty/blob/master/thrifty-schema/src/main/java/com/microsoft/thrifty/schema/Linker.java#L300-L308).

**Comment by hzsweers** [comment]
Nice!
