### ISSUE TITLE
Timeline for 3.0 release

### ISSUE THREAD

**Issue by shashachu** [microsoft/thrifty#448]
I'm checking in to see if there's a rough timeline for a 3.0 release. We're going to need to fork thrifty to apply (yet another) enum generation change (it's too crazy to submit to mainline), and ideally I'd make the change on 3.0 than make it on 2.1.2 and then again on 3.0

Thanks again for all the hard work!

**Comment by benjamin-bader** [comment]
Ooh, sounds like fun!

I haven't made a priority of shipping 3.0.0 lately; other stuff has taken priority.  I'll take a look at what's outstanding and see what a reasonable timeline looks like.

**Comment by benjamin-bader** [comment]
It's been a minute!  Happily, it seems there isn't all that much left to do before shipping 3.0.0 - mostly just tidying up, like updating the compiler flags and the readme.  Given my schedule lately, this means days not weeks.  Thanks for bearing with the glacial pace of development.

**Comment by benjamin-bader** [comment]
@shashachu 3.0.0-RC01 is up on Maven Central now, or will be in 5-15 minutes.  Give it a whirl and let me know if you hit anything weird.

**Comment by shashachu** [comment]
Thank you! We'll check it out.

**Comment by benjamin-bader** [comment]
@shashachu Any update?  I'm curious to hear if you hit any issues, or even just how the internal fork is going, if nothing else.

**Comment by shashachu** [comment]
@benjamin-bader sorry, got distracted with some other work stuff. I'm planning on testing it out this week. Will let you know. Thanks!

**Comment by shashachu** [comment]
@benjamin-bader just started testing and I might be doing something silly, but gradle seems to want the 3.0.0-RC01 runtime, which isn't available on MC:

```
 > Could not find com.microsoft.thrifty:thrifty-runtime:3.0.0-RC01.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/microsoft/thrifty/thrifty-runtime/3.0.0-RC01/thrifty-runtime-3.0.0-RC01.pom
       - file:/Users/shasha/code/android/ReactNative/maven/com/microsoft/thrifty/thrifty-runtime/3.0.0-RC01/thrifty-runtime-3.0.0-RC01.pom
       - https://repo.maven.apache.org/maven2/com/microsoft/thrifty/thrifty-runtime/3.0.0-RC01/thrifty-runtime-3.0.0-RC01.pom
       - file:/Users/shasha/code/android/Pinterest/src/main/libs/thrifty-runtime-3.0.0-RC01.jar
       - file:/Users/shasha/code/android/Pinterest/src/main/libs/thrifty-runtime.jar
       - https://jitpack.io/com/microsoft/thrifty/thrifty-runtime/3.0.0-RC01/thrifty-runtime-3.0.0-RC01.pom
       - https://artifacts-prod-use1.pinadmin.com/artifactory/maven_thirdparty-jar-bazel-prod-local/com/microsoft/thrifty/thrifty-runtime/3.0.0-RC01/thrifty-runtime-3.0.0-RC01.pom
     Required by:
         project :library:schemas > com.microsoft.thrifty:thrifty-compiler:3.0.0-RC01 > com.microsoft.thrifty:thrifty-java-codegen:3.0.0-RC01
         project :library:schemas > com.microsoft.thrifty:thrifty-compiler:3.0.0-RC01 > com.microsoft.thrifty:thrifty-kotlin-codegen:3.0.0-RC01
```

**Comment by benjamin-bader** [comment]
@shashachu I was wondering about this yesterday - it seems that the Kotlin Multiplatform publication support might have changed the artifact name to `thrifty-runtime-jvm`.  I'd like to fix that before releasing, but in the meantime try that and see if it unblocks you.

**Comment by benjamin-bader** [comment]
Huh.  Or maybe it was just a bug in the publishing plugin: https://github.com/vanniktech/gradle-maven-publish-plugin/pull/195

I'll try to push a 3.0.0-RC02 release and see if that fixes things.

**Comment by benjamin-bader** [comment]
3.0.0-RC02 is live in Maven Central, or will be in 10-15 minutes.  Let me know if that resolves the missing-dependency problem!

**Comment by shashachu** [comment]
RC02 works! I'll kick off our test suite now and report back if there appear to be any issues. Thanks for your patience!

**Comment by shashachu** [comment]
@benjamin-bader still working, but one strange thing I noticed: we have a couple structs with a member named `value` and those seem to be generated as `value_` in Kotlin. Is this intentional?

**Comment by benjamin-bader** [comment]
Yeah, this was due to a [change in Kotlinpoet](https://github.com/square/kotlinpoet/blame/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt#L248), the library we use to generate Kotlin code.  They modify names that potentially clash with keywords, and `value` is soon to be a Kotlin keyword.

**Comment by shashachu** [comment]
Looks like no big issues with 3.0.0 - our test suites all passed. 🎉

**Comment by shashachu** [comment]
@benjamin-bader are their any planned changes before officially going to 3.0.0? i may go ahead and just upgrade us to the RC02.

**Comment by benjamin-bader** [comment]
Nope, no plans.  If this thing works as-is, I'm ready to call it a release.

**Comment by benjamin-bader** [comment]
3.0.0 is live in Maven Central, finally.
