### ISSUE TITLE
Struct-valued constants are not yet implemented

### ISSUE THREAD

**Issue by janarajan** [microsoft/thrifty#466]
As it stands today, the current thrifty schema is not able to parse struct valued constants. Wanted to know if this is a work in progress? If not, was this something consciously left out from implementation?

I am trying to load schemas for manipulating certain exceptions based on added annotations. Given that we only care about exceptions structs, is it possible to silently fail the constant schema generation so that it does not throw `IllegalStateException`? 

Several of our thrift definitions have struct valued constants so wondering if there is any workaround?

**Comment by janarajan** [comment]
I will provide a PR to support Schema loading with struct valued constants. The code-gen part can be added as another diff when the requirement arises.

**Comment by benjamin-bader** [comment]
This sounds _vaguely_ familiar.  I'm pretty sure we could support this but it won't be trivial - the `Loader` will need to learn how to link/validate the struct types, for one.

Does the Apache compiler have this feature?  I scanned through their code and, though I can't be sure, it doesn't seem so (e.g. https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/parse/t_const_value.h#L47).

**Comment by benjamin-bader** [comment]
Answering my own question: "yes, it _does_ support struct/exception-valued constants":
https://github.com/apache/thrift/blob/master/compiler/cpp/src/thrift/main.cc#L799

**Comment by janarajan** [comment]
Thanks, @benjamin-bader for the pointers. The apache compiler does support it as we have plenty of struct-defined constants and use the generated code. I am taking a stab at the `Loader` to see if I can add a ConstValidator implementation for struct valued constants. The `AntlrThrift.g4` has support for loading the struct valued constant as the grammar is in line with what Thrift grammar has.

AntlrThrift.g4

`
constDef
        : 'const' fieldType IDENTIFIER '=' constValue separator?
        ;
`

https://thrift.apache.org/docs/idl#const

`
Const           ::=  'const' FieldType Identifier '=' ConstValue ListSeparator?
`

I will leave out the code gen part at this time as the immediate requirement is to be able to load the schema.

**Comment by benjamin-bader** [comment]
Nice, I'll look forward to it!  It's been so long since I've worked on the schema project that I completely forgot that we absolutely _did_ intend to do this.  Turns out we never had the need so it fell off my radar.

You're right that `ConstValidator` is where the work needs to happen; sounds like you've already figured out everything you need.  Let me know how I can help, if you hit any issues!
