### ISSUE TITLE
Question/feature request: Add header/comments to each file

### ISSUE THREAD

**Issue by shashachu** [microsoft/thrifty#485]
I poked through the code and docs and didn't see anything - is there a way to add a common header to every generated file? We've had a couple folks not realize the files are auto-generated and try to hand-edit them. There used to be the `@Generated` annotation but that got removed when the project moved to Kotlin MPP, but being able to add a Javadoc header would be even better.

**Comment by benjamin-bader** [comment]
There's nothing at present.  IIRC we had (have?) that for generated Java sources.  It's trivial to add, and I'm not opposed.

**Comment by benjamin-bader** [comment]
Yep, it's still there for Java: https://github.com/microsoft/thrifty/blob/master/thrifty-java-codegen/src/main/kotlin/com/microsoft.thrifty.gen/ThriftyCodeGenerator.kt#L192

**Comment by shashachu** [comment]
@benjamin-bader cool. I'll put up a PR. Thanks!

**Comment by benjamin-bader** [comment]
Hi @shashachu - JFYI I released version 3.1.0-RC02, containing this fix.  It should be available within the next 10-15 minutes on Maven Central.
