### ISSUE TITLE
Using thrifty-plugins with the thrifty gradle plugin

### ISSUE THREAD

**Issue by amorozov** [microsoft/thrifty#489]
This is not an issue but rather a question. Unfortunately I haven't find any other way to ask this question.

Is it possible to use thifty-plugins together with thrifty gralde plugin? How such a build.gradle[.kts] could look like?

I have tried to extend thriftyClasspath for the `generateThriftyFiles` task like this:

    val thrifty: Configuration = configurations.create("thrifty")
    dependencies {
        thrifty("org.sample:sample-thrifty-plugins:1.0")
        thrifty("com.microsoft.thrifty:thrifty-compiler:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-java-codegen:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-kotlin-codegen:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-schema:3.0.0")
        ...
    }
    tasks {
        named<ThriftyTask>("generateThriftFiles") {
            val cp = thrifty.map { it }.toTypedArray()
            thriftyClasspath.from(*cp)
        }
    }

but apparently it doesn't work.

However, it does work if I use a JavaExec approach like this:

    val thrifty: Configuration = configurations.create("thrifty")
    dependencies {
        thrifty("org.sample:sample-thrifty-plugins:1.0")
        thrifty("com.microsoft.thrifty:thrifty-compiler:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-java-codegen:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-kotlin-codegen:3.0.0")
        thrifty("com.microsoft.thrifty:thrifty-schema:3.0.0")
        ...
    }
    val thriftyGeneratedDir = buildDir.resolve("generated/sources/thrifty")
    val thriftSources = arrayOf("sample.thrift")
    tasks {
        val generateThrifty = register<JavaExec>("generateThrifty") {
            group = "thrifty"
            doFirst {
                thriftyGeneratedDir.mkdirs()
            }
    
            workingDir = file("src/main/thrift")
            classpath = thrifty
    
            mainClass.set("com.microsoft.thrifty.compiler.ThriftyCompiler")
            args = listOf(
                "--out=$thriftyGeneratedDir",
                "--lang=kotlin",
                "--kt-file-per-type",
                "--service-type=coroutine",
                "--omit-file-comments",
                *thriftSources
            )
    
            inputs.dir(workingDir)
            outputs.dir(thriftyGeneratedDir)
    
            logging.captureStandardOutput(LogLevel.WARN)
            logging.captureStandardError(LogLevel.ERROR)
        }
    }

**Comment by benjamin-bader** [comment]
1) Great question!
2) It's a very clever idea, trying to extend the worker classpath that way - I wouldn't have thought of that.  Too bad it didn't work, though I'm kind of curious about _why_ because it seems like it should.

There's no official way to run plugins via the gradle plugin because the need has never arisen and I haven't previously thought about it.  I like your JavaExec solution as a one-off, but will have to think about how to make this work "properly".

**Comment by amorozov** [comment]
Thank you very much for the prompt response and for your efforts to solve it! If you need my assistance I will be glad to help.

**Comment by benjamin-bader** [comment]
With #490, your first effort at using the gradle plugin (extending the thrifty classpath) should work.  As a bonus, you don't even have to specify the other thrifty libs - just your plugin.  (the thrifty libs are already on the classpath).

I'll open a new issue to track API design and testing; in the meantime will make a point release.

**Comment by amorozov** [comment]
Ok, thank you! I will check it as soon as possible.

**Comment by benjamin-bader** [comment]
Version 3.1.0-RC02 contains this fix, and should be available on Maven Central and the Gradle Plugin Portal within the next 10-15 minutes.

**Comment by amorozov** [comment]
Works like a charm, thank you a lot!

**Comment by benjamin-bader** [comment]
Glad to hear it - thanks for confirming!

**Comment by benjamin-bader** [comment]
Finally coming back to this - soon you'll be able to declare a dependency using the new `thriftyTypeProcessor` configuration, like so:

```
dependencies {
  thriftyTypeProcessor "org.sample:sample-thrifty-plugins:1.0" // or any other notation like project(":sample-thrifty-plugins")
}
```
