### ISSUE TITLE
Const definitions referencing imported consts cannot be loaded

### ISSUE THREAD

**Issue by CoolTomatos** [microsoft/thrifty#550]
I have the following two thrift files:
___
`path/to/errors.thrift`
```thrift

const string ERROR_NOT_FOUND = "ErrorNotFound"
...
```
___
`service.thrift`
```thrift
include "path/to/errors.thrift"

const string NOT_FOUND = errors.ERROR_NOT_FOUND
...
```
___
While with Apache Thrift Compiler, I can generate code out of these two thrift files without issues, Thrifty failed to load `service.thrift` with the following error message:
```
E: Unrecognised const identifier: errors.ERROR_NOT_FOUND (at path/to/service.thrift)
```

Right now my workaround is to define `NOT_FOUDN` in `service.thrift` with literal `"ErrorNotFound"` instead of the imported reference `errors.ERROR_NOT_FOUND`.

**Comment by benjamin-bader** [comment]
Thanks for the issue report and the PR!  Can you elaborate a little more on the nature of the problem?  It's not super clear to me whether this is a problem of typedefs, path resolution, or something else entirely.  The linked PR appears to test a case where two different files contain identically-named consts, which is also not reflected in this issue.

**Comment by CoolTomatos** [comment]
Hi @benjamin-bader thanks for the reply.
I think the fundamental problem here, is that with thrifty, we cannot declare a const by referencing an imported constant. 
I will update the issue description to make this more clear.
