### ISSUE TITLE
Enum validation fails when enum is defined in separate thrift file

### ISSUE THREAD

**Issue by seanabraham** [Microsoft/thrifty#63]
We noticed an error like this when running code gen:

`E: 'One' is not a member of enum type Foo: members=[One]`

with `testing_foo.thrift` defined as:
```thrift
namespace java testing 

enum Foo {
  One = 1
}
```

and `testing_bar.thrift` defined as:
```thrift
namespace java testing

include 'testing_foo.thrift'

struct Bar {
  1: required testing_foo.Foo foo = Foo.One;
}
```
(This happens with `required testing_foo.Foo foo = Foo.One` and `required testing_foo.Foo foo = One`)

For reference `required testing_foo.Foo foo = 1` seems to work fine.

It seems like the linking happens correctly, just the validation fails.

**Comment by benjamin-bader** [comment]
Interesting.  My understanding of the IDL spec is that one is required to use the fully-qualified name of imported type; from my perspective, this is working as intended.

Is this behavior different from that of the Apache compiler?

**Comment by yfrancis** [comment]
@benjamin-bader the fully qualified name is used for the field type, the Apache compiler accepts multiple forms:

```
required testing_foo.Foo foo = testing_foo.Foo.One
required testing_foo.Foo foo = Foo.One
required testing_foo.Foo foo = One
required testing_foo.Foo foo = 1
```

Whats interesting is that thrifty links all of these correctly - the type is resolved to the imported enum, its just the constant validation that fails because it does `linker.lookupSymbol("Foo")` rather than `linker.lookupSymbol("testing_foo.Foo")`.

From our investigation, the symbol `testing_foo.Foo` is available at the field level, but when validation is performed on the constant value itself, this information is not passed through.

**Comment by benjamin-bader** [comment]
Thanks @yfrancis, that's really helpful!

Thrift's inconsistencies are going to be the death of me.  I'll have a fix soon.

**Comment by benjamin-bader** [comment]
OK, I've finally got some time to address this.  As I'm looking over the Apache compiler, it certainly appears that unqualified enum references in constants (e.g. `required testing_foo.Foo foo = One`) are *not* accepted; this is as of version 0.9.3.  What version are you using that allows this?

`t_const_value.h` is approximately the same things as Thrifty's `ConstValueElement`, and defines accessors used during const validation.  The ones relevant to enums throw exceptions (i.e. fail) during const validation: https://github.com/apache/thrift/blob/0.9.3/compiler/cpp/src/parse/t_const_value.h#L107

How was this working for you previously?

**Comment by benjamin-bader** [comment]
Just confirmed my reading using the Apache compiler:

a.thrift:
```thrift
namespace java a

enum Foo {
  One
}
```

b.thrift:
```thrift
namespace java b

struct Bar {
  1: required a.Foo foo = One
}
```

```bash
$ thrift -gen java b.thrift
> [FAILURE:/Users/bendb/Development/thrift/b.thrift:6] error: identifier One is unqualified!
```

I'll have a fix for the initial bug, but don't want to deviate from Apache's behavior more than necessary; we'll match this validation behavior.
