### ISSUE TITLE
Can't disambiguate between similar-enough imported enum constants

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/thrifty#66]
A pathological-but-believable scenario might be:

`http_api.thrift`

``` thrift
enum StatusCode {
  NO_ERROR = 1,
  OK = 2,
  // etc
}
```

`other_api.thrift`

``` thrift
enum StatusCode {
  NO_ERROR = 1,
  SUCCESS = 2,
  // etc
}
```

`client.thrift`

``` thrift
struct Response {
  1: required http_api.StatusCode status = StatusCode.NO_ERROR;
}
```

There is certainly enough context in the IDL to know that the correct `StatusCode` is `http_api.StatusCode`, but presently Constant validation doesn't have enough info completely resolve the identifier `StatusCode.NO_ERROR`.  Current behavior has the type resolved non-deterministically - that is, the first matching type to be linked is chosen - and soon we will force a compilation error suggesting that the identifier be fully-qualified.

Apache Thrift gets this right, incidentally.

**Comment by benjamin-bader** [comment]
Ideas:
- Embed `Named` inside of `UserType`s
- Introduce a new `ThriftType` to represent imported types (but keep it internal to `thrifty-schema`)
- Enhance `Constant.validate` to accept a `Named` for the type being validated, if present

I like the last idea best for now, but haven't thought through the ramifications.  Comments welcome, for anyone who cares to join in the thinking.

**Comment by yfrancis** [comment]
I like the idea of embedding `Named` inside of `UserType`. This is similar to Apache Thrift's approach where every `t_type` has an associated `t_program` which corresponds to its original thrift document.
