### ISSUE TITLE
Unify Named with ThriftType

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/thrifty#69]
As time passes, the distinction seems less and less useful.

`ThriftType.UserType` should subsume `Named`, and `ThriftType` in general should become enriched.  This would fix all the fiddly `Constant` validation bugs and simplify lots of requested use cases from @hzsweers and friends.

**Comment by benjamin-bader** [comment]
So - the proposed hierarchy would be:
```
ThriftType
|__BuiltinThriftType (bool,byte,i8,i16,i32,i64,double,string,binary)
|__ListThriftType
|__SetThriftType
|__MapThriftType
|__TypedefThriftType
|__UserThriftType
|  |__EnumThriftType
|  |__StructThriftType (struct, union, exception)
|__ServiceThriftType
```

`UserThriftType` and `ServiceThriftType`, and `Constant` will tentatively implement an interface exposing the same things that `Named` does currently - `Location` and Javadoc.

`Program` would be more or less the same, but everything from `Linker` down changes.  Codegen will presumably be different, though I haven't thought much about it.

**Comment by hzsweers** [comment]
After what we discussed about Typedefs, should they maybe straddle the line with UserThriftType a bit more?

**Comment by benjamin-bader** [comment]
You and I arrived at the same conclusion; I've ended up with both TypedefType and ServiceType extending UserType.  The final hierarchy, then, is

```
ThriftType
|__BuiltinType (bool,byte,i8,i16,i32,i64,double,string,binary)
|__ListType
|__SetType
|__MapType
|__UserType
|  |__EnumType
|  |__StructType (struct, union, exception)
|  |__TypedefType
|  |__ServiceType
```
