### ISSUE TITLE
How do I import and build this in Eclipse?

### ISSUE THREAD

**Issue by divyam01986** [Microsoft/thrifty#86]
I am a beginner to the open source community. I want to know how to import this project into Eclipse and build it. Thank you:).

**Comment by benjamin-bader** [comment]
Hi, welcome to the open source community!  I'm not an Eclipse user, but this is a pretty standard project using Gradle for its build system.  Perhaps Eclipse has documentation about how to import Gradle projects?

**Comment by benjamin-bader** [comment]
(I use IntelliJ for this, which I personally prefer over Eclipse, but both are very capable IDEs)

**Comment by benjamin-bader** [comment]
Any luck?

**Comment by benjamin-bader** [comment]
OK, from your issue about running unit tests it looks like this is resolved.  Glad you got it building!
